---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Get astara migrations facts
  astara_migrations_facts:
    release: newton
    library_path: "{{ astara_lib_dir }}"
    bin_path: "{{ astara_bin }}"

- name: Print astara migrations facts
  debug:
    var: astara_migrations
  when: astara_plugin_type.split('.')[0] == 'ml2'

- name: Perform a Neutron DB online upgrade (expand)
  command: |
    {{ astara_bin }}/astara-db-manage
                      --config-file {{ astara_db_config }}
                      --config-file {{ astara_db_plugin }}
                      upgrade --expand
  become: yes
  become_user: "{{ astara_system_user_name }}"
  when:
    - (astara_migrations is defined and astara_migrations['run_expand']|bool)

- name: Stop the orchectrator
  service:
    name: "astara-orchectrator"
    state: stopped
    pattern: "astara-orchectrator"
  delegate_to: "{{ item }}"
  with_items: "{{ groups[astara_services['astara-orchectrator']['group']] }}"
  when: (astara_migrations is defined and astara_migrations['run_contract']|bool)

- name: Perform a Neutron DB offline upgrade (contract)
  command: |
    {{ astara_bin }}/astara-db-manage
                      --config-file {{ astara_db_config }}
                      --config-file {{ astara_db_plugin }}
                      upgrade --contract
  become: yes
  become_user: "{{ astara_system_user_name }}"
  when:
    - (astara_migrations is defined and astara_migrations['run_contract']|bool)

# NOTE: We have to handle astara_plugin_type.split('.')[0] != 'ml2' because not all astara
#       plugins have contract/expand branches which breaks astara-db-manage.
#       This can be reverted once all plugins are conformant.
- name: Perform a Neutron DB offline upgrade (heads)
  command: |
    {{ astara_bin }}/astara-db-manage
                      --config-file {{ astara_db_config }}
                      upgrade heads
  become: yes
  become_user: "{{ astara_system_user_name }}"

- name: Start astara server
  service:
    name: "astara-server"
    state: started
    pattern: "astara-server"
  delegate_to: "{{ item }}"
  with_items: "{{ groups[astara_services['astara-server']['group']] }}"
  when: (astara_migrations is defined and astara_migrations['run_contract']|bool) 
